Sprint3
ClevertecFrontendLab/Pavel-Loban pull request #1
Opened 2023-02-14 17:20 UTC by Pavel-Loban

2023-02-14 17:23 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 4.
Количество непройденных тестов: 0.
***
**app-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Pavel-Loban/1676395409/app-sucess.png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Pavel-Loban/1676395409/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Pavel-Loban/1676395409/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Pavel-Loban/1676395409/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Pavel-Loban/1676395409/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Pavel-Loban/1676395409/main-loading.png)

2023-02-14 18:05 UTC, vvikota requested changes

2023-02-14 18:05 UTC, vvikota commented on src/pages/book/book-page.tsx
> +                                    <td className={styles.tables_title}>Издательство</td><td >Питер</td>
наименование "издательства" приходит с сервера

2023-02-14 18:05 UTC, vvikota commented on src/pages/book/book-page.tsx
> +                        <div className={styles.wrapper_button_book}>
такие штуки для читабельности нужно отформатировать и можно вообще вынести в отдельный компонент

2023-02-14 18:05 UTC, vvikota commented on src/components/message-after-loading/message.tsx
> +export const Message: React.FC = () => {
это компонент лучше назвать Toast или Alert

2023-02-16 13:46 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.
***
**Get books test -- getCategoriesAndBooks -- categories-loading (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Pavel-Loban/1676555208/Get%20books%20test%20--%20getCategoriesAndBooks%20--%20categories-loading%20(failed).png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Pavel-Loban/1676555208/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Pavel-Loban/1676555208/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Pavel-Loban/1676555208/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Pavel-Loban/1676555208/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Pavel-Loban/1676555208/main-loading.png)

2023-02-16 14:22 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 4.
Количество непройденных тестов: 0.
***
**app-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Pavel-Loban/1676557356/app-sucess.png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Pavel-Loban/1676557356/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Pavel-Loban/1676557356/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Pavel-Loban/1676557356/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Pavel-Loban/1676557356/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Pavel-Loban/1676557356/main-loading.png)

2023-02-16 15:18 UTC, merged